[package]
name = "xva-parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.20.10"
xva-ast = { path = "../xva-ast" }
xva-treesitter = { path = "../xva-treesitter" }
