[package]
name = "xvabuildinfo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
build-info = "0.0.31"
build-info-common = "0.0.31"

[build-dependencies]
build-info-build = "0.0.31"