[package]
name = "xva-compiler"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xva-span = { path = "../xva-span" }
xva-parse = { path = "../xva-parse" }
xva-hir = { path = "../xva-hir" }
xva-ast = { path = "../xva-ast" }
